/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fraktale.org.solbach.fraktale;

//import fraktale.org.solbach.fraktale.Hüpfer;

/**
 *
 * @author csolb
 */
@SuppressWarnings("serial")
public class HüpferDialog extends javax.swing.JDialog {

    /**
     * Creates new form HüpferDialog
     * @param parent
     * @param modal
     */
   public HüpferDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    // initComponents(); // Falls du NetBeans GUI-Builder nutzt
    
    // Statt paintComponents hier lieber die Größe und Position festleg
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        parametera = new javax.swing.JTextField();
        parameterb = new javax.swing.JTextField();
        parameterc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        parameterz = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Parameter a");

        jLabel2.setText("Parameter b");

        jLabel4.setText("Parameter c");

        parametera.setColumns(10);
        parametera.setText("0.97");
        parametera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HüpferDialog.this.focusGained(evt);
            }
        });
        parametera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameteraActionPerformed(evt);
            }
        });
        parametera.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                parameteraPropertyChange(evt);
            }
        });
        Hüpfer.mainframe.a=Double.parseDouble(parametera.getText()  );

        parameterb.setColumns(10);
        parameterb.setText(".3456");
        Hüpfer.mainframe.b=Double.parseDouble(parameterb.getText());
        parameterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterbActionPerformed(evt);
            }
        });

        parameterc.setColumns(10);
        parameterc.setText("50");
        parameterc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametercActionPerformed(evt);
            }
        });
        Hüpfer.mainframe.c=Double.parseDouble(parameterc.getText());

        jLabel5.setText("Iterationstiefe");

        parameterz.setColumns(10);
        parameterz.setText("30000");
        Hüpfer.mainframe.c=Long.parseLong(parameterc.getText());  
        parameterz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parametera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parameterc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parameterz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parameterb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(parametera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parameterb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(parameterc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(parameterz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parameterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterbActionPerformed
        // TODO add your handling code here:
       // Hüpfer.mainframe.b=Double.parseDouble(parameterb.getText());
        //Hüpfer.mainframe.paintComponent1(Hüpfer.mainframe.getGraphics());
        Hüpfer.mainframe.b=Double.parseDouble(parameterb.getText());
       Hüpfer.mainframe.repaint();
    }//GEN-LAST:event_parameterbActionPerformed

    private void parameteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameteraActionPerformed
        // TODO add your handling code here:
         //Hüpfer.mainframe.a=Double.parseDouble(parametera.getText());
       //Hüpfer.mainframe.paintComponent1(Hüpfer.mainframe.getGraphics());
       Hüpfer.mainframe.a=Double.parseDouble(parametera.getText());
        Hüpfer.mainframe.repaint();
    }//GEN-LAST:event_parameteraActionPerformed

    private void parametercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametercActionPerformed
        // TODO add your handling code here:
        // Hüpfer.mainframe.c=Double.parseDouble(parameterc.getText());
       //Hüpfer.mainframe.paintComponent1(Hüpfer.mainframe.getGraphics());
       Hüpfer.mainframe.c=Double.parseDouble(parameterc.getText());
        Hüpfer.mainframe.repaint();
    }//GEN-LAST:event_parametercActionPerformed

    private void parameterzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterzActionPerformed
        // TODO add your handling code here:
        // Hüpfer.mainframe.z=Long.parseLong(parameterz.getText());
        //Hüpfer.mainframe.paintComponent1(Hüpfer.mainframe.getGraphics());
         Hüpfer.mainframe.z=Long.parseLong(parameterz.getText());
          Hüpfer.mainframe.repaint();
       
    }//GEN-LAST:event_parameterzActionPerformed

    private void parameteraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_parameteraPropertyChange
        // TODO add your handling code here:
       /* Hüpfer.mainframe.c=Double.parseDouble(parameterc.getText());
        
        
        
        
        Hüpfer.mainframe.paintComponent1(Hüpfer.mainframe.getGraphics());
        repaint(0);*/
    }//GEN-LAST:event_parameteraPropertyChange

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
                // TODO add your handling code here:
             //   Hüpfer.mainframe.a=Double.parseDouble(parametera.toString());  
    }//GEN-LAST:event_focusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HüpferDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HüpferDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HüpferDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HüpferDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            HüpferDialog dialog = new HüpferDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.initComponents();
            dialog.pack();
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField parametera;
    private javax.swing.JTextField parameterb;
    private javax.swing.JTextField parameterc;
    private javax.swing.JTextField parameterz;
    // End of variables declaration//GEN-END:variables
}
